<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Dto\**" />
    <Compile Remove="Interfaces\**" />
    <Compile Remove="Validation\**" />
    <EmbeddedResource Remove="Dto\**" />
    <EmbeddedResource Remove="Interfaces\**" />
    <EmbeddedResource Remove="Validation\**" />
    <None Remove="Dto\**" />
    <None Remove="Interfaces\**" />
    <None Remove="Validation\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.11" />
  </ItemGroup>

</Project>
